route:
  receiver: "slack"

receivers:
  - name: "slack"
    slack_configs:
      - send_resolved: true
        username: "alert_manager"
        channel: "#prometheus"
        api_url: "<REPLACE_WITH_SLACK_WEBHOOK>"
