route:
  receiver: "slack"

receivers:
  - name: "slack"
    slack_configs:
      - send_resolved: true
        username: "alert_manager"
        channel: "#prometheus"
        api_url: "https://hooks.slack.com/services/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"
